### ISSUE TITLE
Separate transistion for ng-enter and ng-leave

### ISSUE THREAD

**Issue by bitflower** [cgwyllie/angular-velocity#11]
Hi, this would help very much.

Or do I miss something? I think the opposites solution is to reverse an animation in general but not to run the reversed animation on ng-leave, right?

**Comment by jameswyse** [comment]
Would it be possible to define animations that slide in/out in the same direction? ie `slideLeftIn` on entry and `slideLeftOut` on leave?

**Comment by cgwyllie** [comment]
@jameswyse Right now, that's not possible, but thanks for suggesting it -- I think that makes a lot of sense.

Is there a syntax you were thinking of? Or do you want to manually specify the enter and leave transitions separately?

Thanks

**Comment by alexisohayon** [comment]
Hi,

Is it possible to have an animation on enter, but disabling it on leave?
I have a form that I want to display on click, and to hide if clicking outside the form. 
I prefer the hidding to be immediate than animated (I hope it's understandable :) )

**Comment by cgwyllie** [comment]
Hi @alexisohayon,

Absolutely what you're suggesting is understandable. At the moment, this isn't possible although I think in a future version it would definitely be a good feature to have, although the syntax would maybe have to change a little bit to support more flexible configurations.

Any thoughts you have on this would be welcome :)

**Comment by alexisohayon** [comment]
Yeah, I was thinking of doing this the same way you do the "opposite", we could specify "enter" or "leave" in the class name, or leave empty by default so your directive knows what to animate. 
What do you think? 
Do you have an idea of when something like this could be released? :)

**Comment by cgwyllie** [comment]
@alexisohayon Thanks for the input! Sorry it's taken a while, but this has landed in 0.3.0!

Thanks to everyone who requested this and discussed, I'm marking it as closed with the 0.3.0 release.

Please feel free to create a new issue if there's anything else related to this!

**Comment by alexisohayon** [comment]
Thanks dude that's awesome! :)

**Comment by bitflower** [comment]
Late to the party - great, thanks @cgwyllie
