### ISSUE TITLE
Velocity 1.2.x

### ISSUE THREAD

**Issue by cgwyllie** [cgwyllie/angular-velocity#14]
Need to pull in latest Velocity and give things a test, check for any new features etc.

**Comment by ajmajma** [comment]
Hey @cgwyllie hope your'e doing well! I an issue with an ng-show in a repeat using the opposites method, and i believe it has to do with the newest velocity. It's giving me an 'Undefined is not a function' when I try to swap what is shown and what is not in a repeat. The top of the error stack is pointing to - $el.velocity(animation, opts); on line 139. This method i was using was working about 2 weeks ago. Thanks!

**Comment by mkoryak** [comment]
+1

**Comment by cgwyllie** [comment]
Updated in 0.2.3 release. Please open an issue if any problems!
