### ISSUE TITLE
Staggering no repeat problem

### ISSUE THREAD

**Issue by tushariscoolster** [cgwyllie/angular-velocity#17]
when u activate stagger, last element of ngrepeat stays on ui even if u clear the scope,

**Comment by cgwyllie** [comment]
Hi @tushariscoolster,

Thanks for reporting this. Could you provide a small code snip with some reproduction steps? In particular I'm interested in how you're clearing the scope and what options/transitions you're using.

Thanks,
Chris

**Comment by tushariscoolster** [comment]
http://jsfiddle.net/6t42M/155/ 
???

**Comment by cgwyllie** [comment]
Yikes! That's pretty broken! Thanks for the example to help see the issue in action..

I'll need to dig in to the stagger queueing code to see what's going on. Seems to happen even if the `stagger` option is not passed, I think it has something to do with done callbacks not being fired correctly.

Thanks for reporting, hope to have this resolved soon.

**Comment by cgwyllie** [comment]
@tushariscoolster Hey, I've just pushed out 0.2.4 which I believe addresses this issue.

Please feel free to reopen if you're still seeing bugged behaviour after updating!

Thanks again for reporting this!

**Comment by tushariscoolster** [comment]
Let me check;
thanks a lot man!!
have a gud day!!
