### ISSUE TITLE
Disable animation

### ISSUE THREAD

**Issue by alexborisov** [cgwyllie/angular-velocity#22]
Is there any way to disable animation in one direction? For instance enable enter animations and disable exit animations. I assumed that if i set `velocity-enter-transition` instead of `velocity-transition` it would do exactly this, but it seems that the exit animations are always enabled.

**Comment by cgwyllie** [comment]
@alexborisov Oh dear, this sounds like a bug!

Could you give a snippet of your markup with the transition classes and how you're showing/hiding the element?

Thanks

**Comment by alexborisov** [comment]
I created a separate project just for this test case and have been unable to replicate the issue. My guess it's a bug in my styling/logic. Sorry for the false alarm!
