### ISSUE TITLE
Angular-Velocity and mobile performances

### ISSUE THREAD

**Issue by PierrickGT** [cgwyllie/angular-velocity#23]
Hello everybody,

I'm planning to use angular-velocity on a mobile version of a website and I was wondering if any of you already used it for this kind of project and if the animations are as fluid as on desktop. 

Thank you by advance.

**Comment by hellsan631** [comment]
Angular-Velocity makes use of the VelocityJS framework, which improves performance of mobile platform animations over using JQuery or standard CSS3 transitions, and is the best animation library in those terms..

**Comment by PierrickGT** [comment]
Thank you for your answer!
