### ISSUE TITLE
Angular 1.2.x support?

### ISSUE THREAD

**Issue by mydearxym** [cgwyllie/angular-velocity#24]
amazing work!
my project is based on Angular-1.2.x ,  is this project support angular1.2.x?

**Comment by cgwyllie** [comment]
Hi!

I don't believe there is any reason it shouldn't still work with 1.2.x, probably the bower dependencies file is just set up with more recent versions so it _looks_ like it won't.

I would say give it a go and let me know if there are any issues!

**Comment by mydearxym** [comment]
it does work with angular1.2 !!   it's cool~
