### ISSUE TITLE
How do I do things like {translateX : [0, 50]}

### ISSUE THREAD

**Issue by sharpmachine** [cgwyllie/angular-velocity#32]
How do I things other then just transitions and callouts that velocity.js provides? Like `{translateX : [0, 50]}`?

**Comment by cgwyllie** [comment]
So arbitrary animation chains are not supported, but defining custom transitions is. You can see a rough example of this here: https://github.com/cgwyllie/angular-velocity/issues/3#issuecomment-70532609

Can I ask for more context on your intended use case? I'm curious how you'd want to use arbitrary translations etc., sounds like it could be useful.

**Comment by cgwyllie** [comment]
Possibly related to #29

**Comment by sharpmachine** [comment]
Things like transitioning between tabs, etc. The transition.slideLeftIn for example adds a fade, which I don't want so just having total control to really fine tune the animations is a big thing. Animations add some much context and meaning for the user when done well so have control over the details is key. 

I've figured out I can create my animations like so:

``` javascript
var ngModule = angular.module('YourApp', ['ngAnimate']);
ngModule.animation('.my-crazy-animation', function() {
  return {
    enter: function(element, done) {
      //run the animation here and call done when the animation is complete
      element.velocity({translateX:[0,50]});
      return function(cancelled) {
        //this (optional) function will be called when the animation
        //completes or when the animation is cancelled (the cancelled
        //flag will be set to true if cancelled).
      };
    },
    leave: function(element, done) { },
    move: function(element, done) { },

    //animation that can be triggered before the class is added
    beforeAddClass: function(element, className, done) { },

    //animation that can be triggered after the class is added
    addClass: function(element, className, done) { },

    //animation that can be triggered before the class is removed
    beforeRemoveClass: function(element, className, done) { },

    //animation that can be triggered after the class is removed
    removeClass: function(element, className, done) { }
  };
});
```

So I can get the control I need using Velocity that way. This may be obvious to a genius coder such as yourself. I'm a UX designer trying to prototype in Angular. But I'm hoping to do a good job on the code so at least 90% of it will make it into production.

Thanks for your help.

**Comment by cgwyllie** [comment]
@sharpmachine Cool! Sadly there is nothing obvious about Angular's animation stuff...
